// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc4089.Stealth2018.commands.*;
import org.usfirst.frc4089.Stealth2018.subsystems.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick driveStick;
    public JoystickButton runShooter;
    public JoystickButton reverseShooter;
    public JoystickButton stopShooter;
    public JoystickButton runEllevator;
    public JoystickButton reverseEllevator;
    public JoystickButton stopEllevator;
    public JoystickButton extendCollector;
    public JoystickButton retractCollector;
    public JoystickButton runCollector;
    public JoystickButton stopCollector;
    public JoystickButton reverseCollector;
    public JoystickButton climbUp;
    public JoystickButton climbDown;
    public JoystickButton automatedShooter;
    public JoystickButton debug;
    public JoystickButton shooterDoorOpen;
    public JoystickButton shooterDoorClose;
    public JoystickButton agitate;
    public JoystickButton stopAgitate;
    public JoystickButton blockOuterBarrels;
    public JoystickButton openOuterBarrels;
    public Joystick utilityStick;
    public XboxController xboxController1;
    

    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        utilityStick = new Joystick(2);
        driveStick = new Joystick(1);
        xboxController1 = new XboxController(0);
        
        
        /*climbDown = new JoystickButton(utilityStick, 8);
        climbDown.whileHeld(new ClimberDown());*/
        climbUp = new JoystickButton(utilityStick, 8);
        climbUp.whileHeld(new ClimberUp());
        reverseCollector = new JoystickButton(utilityStick, 5);
        reverseCollector.whenPressed(new CollectorReverse());
        stopCollector = new JoystickButton(utilityStick, 3);
        stopCollector.whenPressed(new CollectorStop());
        runCollector = new JoystickButton(utilityStick, 4);
        runCollector.whenPressed(new CollectorRun());
        stopEllevator = new JoystickButton(driveStick, 10);
        stopEllevator.whenPressed(new EllevatorStop());
        runEllevator = new JoystickButton(utilityStick, 9);
        runEllevator.whileHeld(new EllevatorRun());
        reverseEllevator = new JoystickButton(driveStick, 12);
        reverseEllevator.whenPressed(new EllevatorReverse());
        stopShooter = new JoystickButton(utilityStick, 10);
        stopShooter.whenPressed(new ShooterStop());
        runShooter = new JoystickButton(utilityStick, 11);
        runShooter.whenPressed(new ShooterRun());
        reverseShooter = new JoystickButton(driveStick, 11);
        reverseShooter.whenPressed(new ShooterReverse());
        automatedShooter = new JoystickButton(utilityStick, 1);
        automatedShooter.whenPressed(new AutomatedShooting());
        /*shooterDoorOpen = new JoystickButton(utilityStick, 11);
        shooterDoorOpen.whenPressed(new ShooterDoorOpen());
        shooterDoorClose = new JoystickButton(utilityStick, 10);
        shooterDoorClose.whenPressed(new ShooterDoorClose());
        */
        agitate = new JoystickButton(utilityStick, 2);
        agitate.whileHeld(new Agitate());
        blockOuterBarrels = new JoystickButton(utilityStick, 6);
        blockOuterBarrels.whenPressed(new BlockOuterBarrels());
        openOuterBarrels = new JoystickButton(utilityStick, 7);
        openOuterBarrels.whenPressed(new OpenOuterBarrels());
        debug = new JoystickButton(driveStick, 4);
        debug.whenPressed(new Debug());
        
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("ShooterRun", new ShooterRun());
        SmartDashboard.putData("ShooterStop", new ShooterStop());
        SmartDashboard.putData("EllevatorStop", new EllevatorStop());
        SmartDashboard.putData("EllevatorRun", new EllevatorRun());
        SmartDashboard.putData("CollectorRun", new CollectorRun());
        SmartDashboard.putData("CollectorStop", new CollectorStop());
        SmartDashboard.putData("CollectorIn", new CollectorIn());
        SmartDashboard.putData("CollectorOut", new CollectorOut());
        SmartDashboard.putData("ClimberUp", new ClimberUp());
        SmartDashboard.putData("ClimberDown", new ClimberDown());
        SmartDashboard.putData("DriveF", new AutoDriveFTimed());
        SmartDashboard.putData("UserDrive", new UserDrive());
        SmartDashboard.putData("AutomatedShooting", new AutomatedShooting());
        SmartDashboard.putData("HalfSecondDelay", new SpinUpDelay());
        SmartDashboard.putData("ShootingDelay", new ShootingDelay());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriveStick() {
        return driveStick;
    }

    public Joystick getUtilityStick() {
        return utilityStick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public XboxController getXboxController(){
    	return xboxController1;
    }

}

